### PR TITLE
docker: use host timezone

### PR DESCRIPTION
**Pull request by Zaphkito**

### CODE REVIEW

**Comment by hykilpikonna** [comment]
Not all host OS are Unix tho

**Comment by Zaphkito** [comment]
> Not all host OS are Unix tho

isn't Docker for Windows just some emulation to Unix then create a container? I remember that depend on Hyper-V, and setup guide recommend me install that

my machine can't install Hyper-V or other in Windows, because that conflict with my other program/service, can you test it when you have time and tell me did it work?

**Comment by AsakuraMizu** [comment]
This is not needed. Set environment variable `TZ` like `TZ=Asia/Shanghai` to change the timezone.

**Comment by hykilpikonna** [comment]
Just tested this. On Windows, the values in /etc/timezone and /etc/localtime doesn't reflect the actual system timezone but rather returns UTC. So I think setting the environment variable would be a better solution

image

**Pull request closed without merging**
